[project]
name = "django-starsweb"
version = "2.0.0"
requires-python = ">= 3.10"
authors = [
  {name = "Jeff Bradberry", email = "jeff.bradberry@gmail.com"},
]
description = "A hosting app for the classic 4X space strategy game Stars."
readme = "README.rst"
license = "MIT"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Games/Entertainment :: Turn Based Strategy",
]

[project.entry-points."turngeneration.plugins"]
starsweb = "starsweb.plugins:TurnGeneration"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["starsweb"]
