# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2025-12-05 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starsweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='markup_type',
        ),
        migrations.RemoveField(
            model_name='racepage',
            name='markup_type',
        ),
    ]
