# Generated by Django 3.2.25 on 2025-12-17 17:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('starsweb', '0002_remove_markup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('S', 'Setup'), ('A', 'Active'), ('P', 'Paused'), ('F', 'Finished')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='accelerated_bbs',
            field=models.BooleanField(blank=True, default=False, help_text='Players start with 4 times the normal population, and planets have 20% more minerals.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='ai_players',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='computer_alliances',
            field=models.BooleanField(blank=True, default=False, help_text='Computer players will prefer to attack human players instead of each other.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='galaxy_clumping',
            field=models.BooleanField(blank=True, default=False, help_text='Causes star systems to clump together.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='maximum_minerals',
            field=models.BooleanField(blank=True, default=False, help_text='All planets start with a mineral concentration of 100. Not recommended for experienced players.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='public_scores',
            field=models.BooleanField(blank=True, default=True, help_text="All player's scores will be displayed in the score sheet after the first 20 turns."),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='random_events',
            field=models.BooleanField(blank=True, default=True, help_text='Allow random occurrences such as Mystery Traders, comets, and wormholes.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='slow_tech',
            field=models.BooleanField(blank=True, default=False, help_text='Research will be twice as expensive.'),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='starting_distance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Close'), (1, 'Moderate'), (2, 'Farther'), (3, 'Distant')], default=1),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='universe_density',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sparse'), (1, 'Normal'), (2, 'Dense'), (3, 'Packed')], default=1),
        ),
        migrations.AlterField(
            model_name='gameoptions',
            name='universe_size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Tiny'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Huge')], default=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='section',
            field=models.IntegerField(choices=[(0, 'Rank'), (1, 'Score'), (2, 'Resources'), (3, 'Tech Levels'), (4, 'Capital Ships'), (5, 'Escort Ships'), (6, 'Unarmed Ships'), (7, 'Starbases'), (8, 'Planets')], default=0),
        ),
        migrations.AlterField(
            model_name='starsfile',
            name='type',
            field=models.CharField(choices=[('r', 'race'), ('xy', 'map'), ('m', 'state'), ('x', 'orders'), ('h', 'history'), ('hst', 'host')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='ambassador',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userrace',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ambassador',
            constraint=models.UniqueConstraint(fields=('race', 'user'), name='ambassador_user_per_race'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='race_slug_per_game'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='race_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('game', 'plural_name'), name='race_plural_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('game', 'player_number'), name='race_player_number_per_game'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('turn', 'race', 'section'), name='score_datapoint'),
        ),
        migrations.AddConstraint(
            model_name='userrace',
            constraint=models.UniqueConstraint(fields=('user', 'identifier'), name='userrace_identifier_per_user'),
        ),
    ]
